In [2]:
import numpy as np
import time

In [ ]:
size = 10000
# python list
pylist = list(range(size))
s = time.time()
sqlist = [x**2 for x in pylist]
e = time.time()
print(f"python list time= {e-s} sec")

# numpy arrays
nparr = np.array(pylist)
s = time.time()
sqarr = nparr**2
e = time.time()
print(f"numpy list time= {e-s} sec")

In [ ]:
import sys

print(f"python list size= {sys.getsizeof(pylist) *len(pylist)}")
print(f"numpy list size= {sys.getsizeof(nparr) *len(nparr)}")

In [ ]:
import numpy as np

a = np.array([10, 2011, 30])
a2 = np.array([10, 11, 30, "s"])
print(a)
print(a2, type(a2), a2.dtype, a2.shape)


aa2 = np.array([[10, 11, 30], [1, 11, 3], [12, 21, 230], [10, 61, 630]])
print(aa2, aa2.shape)

In [ ]:
a = np.zeros((2, 15), dtype=int) 
print(a, a.shape)
a = np.ones((22,), dtype=int) #fill with one
print(a, a.shape)
a = np.full((2, 4), 200, dtype=int) #fill with val given by me
print(a, a.shape)
a = np.eye((4), dtype=int) #identity matrix
print(a, a.shape)
a = np.arange(4,7,2) #range ele
print(a, a.shape,"a")
a = np.linspace(1,90,4) #evenly spaced arr
print(a, a.shape,"aw")


In [ ]:
# properties
a = np.array([[2,3,5,4,6],[2,32,5,4,6],[2,3,5,4,6]])
print(a, a.shape) #print dimensions
print(a, a.ndim) #print dimensions num
print(a, a.size) #print size
fa=a.astype(np.float64)
print(fa,fa.dtype)

In [8]:
# operations
a = np.array([[2,3,5,4,6],[2,32,5,4,6],[2,3,5,4,6]])
print(a, a.shape)
print(a.reshape(5,3).shape)
print(a.reshape(5,3))
print(a.flatten()) #convert 2d to 1d
print(a.flatten().shape)

# indexing
a = np.array([[2,3,5,4,6],[2,32,5,4,6],[2,3,5,4,6]])
id=[1,2] #fancy indexing
print(a[1][1])
print(a[id],"l")
print(a[1, [0,1,2]])#fancy indexing
print(a[a%2==0],"s") #boolean indexing
print(a[1:2:2],"ss") #slicing [s,e,step]


[[ 2  3  5  4  6]
 [ 2 32  5  4  6]
 [ 2  3  5  4  6]] (3, 5)
(5, 3)
[[ 2  3  5]
 [ 4  6  2]
 [32  5  4]
 [ 6  2  3]
 [ 5  4  6]]
[ 2  3  5  4  6  2 32  5  4  6  2  3  5  4  6]
(15,)
32
[[ 2 32  5  4  6]
 [ 2  3  5  4  6]] l
[ 2 32  5]
[ 2  4  6  2 32  4  6  2  4  6] s
[[ 2 32  5  4  6]] ss


In [10]:

a2 = np.array([10, 2011, 30])
print(a2, type(a2), a2.dtype)

[  10 2011   30] <class 'numpy.ndarray'> int64
